modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="gizmod"
version="1.0.0"
displayName="GizMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="gizmo, MCreator"

[[dependencies.gizmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




